/**
 * Variable names the platform or runtime always provides, skipped by default in every section
 * (`--no-default-ignore` brings them back). Globs as for `--ignore`: case-sensitive, anchored.
 *
 * GitHub gets its exact default list, not a `GITHUB_*` prefix: apps define their own GITHUB_ names
 * (an OAuth app's GITHUB_CLIENT_SECRET, a GitHub App's GITHUB_APP_ID), and those must still count.
 */
export const DEFAULT_IGNORE: readonly string[] = [
  // Node, npm, Next.js and the OS.
  'NODE_ENV',
  'NEXT_RUNTIME',
  'npm_*',
  'HOME',
  'PATH',
  'PWD',
  'USER',
  'SHELL',
  'TMPDIR',
  'HOSTNAME',
  // CI, and GitHub Actions' default variables (docs.github.com, "Variables reference").
  'CI',
  'GITHUB_ACTION',
  'GITHUB_ACTION_PATH',
  'GITHUB_ACTION_REPOSITORY',
  'GITHUB_ACTIONS',
  'GITHUB_ACTOR',
  'GITHUB_ACTOR_ID',
  'GITHUB_API_URL',
  'GITHUB_ARTIFACTS',
  'GITHUB_ARTIFACTS_LIST',
  'GITHUB_BASE_REF',
  'GITHUB_ENV',
  'GITHUB_EVENT_NAME',
  'GITHUB_EVENT_PATH',
  'GITHUB_GRAPHQL_URL',
  'GITHUB_HEAD_REF',
  'GITHUB_JOB',
  'GITHUB_OUTPUT',
  'GITHUB_PATH',
  'GITHUB_REF',
  'GITHUB_REF_NAME',
  'GITHUB_REF_PROTECTED',
  'GITHUB_REF_TYPE',
  'GITHUB_REPOSITORY',
  'GITHUB_REPOSITORY_ID',
  'GITHUB_REPOSITORY_OWNER',
  'GITHUB_REPOSITORY_OWNER_ID',
  'GITHUB_RETENTION_DAYS',
  'GITHUB_RUN_ATTEMPT',
  'GITHUB_RUN_ID',
  'GITHUB_RUN_NUMBER',
  'GITHUB_SERVER_URL',
  'GITHUB_SHA',
  'GITHUB_STEP_SUMMARY',
  'GITHUB_TRIGGERING_ACTOR',
  'GITHUB_WORKFLOW',
  'GITHUB_WORKFLOW_REF',
  'GITHUB_WORKFLOW_SHA',
  'GITHUB_WORKSPACE',
  'RUNNER_*',
  // Hosting platforms' system variables.
  'VERCEL',
  'VERCEL_*',
  'NEXT_PUBLIC_VERCEL_*',
  'RAILWAY_*',
  'RENDER',
  'RENDER_*',
  'FLY_*',
];
